### ISSUE TITLE
[Core] App: log_in_with_credentials failed: 0 message: java.io.IOException: Required SETTINGS preface not received

### ISSUE THREAD

**Issue by nil-engineer** [stevdza-san/DiaryApp#3]
I'm following your "Complete multimodular architecture for android development" course.
When I implemented the onetap signin with google and create a user on a Mongo DB Atlas and run the project on a real android device, I got this error : 
2023-10-09 12:04:33.044  8529-8605  REALM                   com.androiddev.diaryapp              W  [Core] App: log_in_with_credentials failed: 0 message: java.io.IOException: Required SETTINGS preface not received

![Screenshot_20231009-121759](https://github.com/stevdza-san/DiaryApp/assets/61160976/a0a8a7fc-b26f-4819-a478-5febe335f34e)

@stevdza-san I couldn't find out the reason of error.

**Comment by stevdza-san** [comment]
I'm seeing that error for the first time. Be sure to check my repo, and compare your code with it. You may have missed something? Also for the CLIENT_ID of the One-Tap Compose, you do need to enter the WEB CLIENT_ID from the google cloud platform project.

**Comment by nil-engineer** [comment]
I compared my code with your repo. Also, I checked the CLIENT_ID again. Everything was right in the code.
But after using VPN I could successfully sign in with Google.
Anyway, thanks for your help.
