### ISSUE TITLE
Issue Report: Login Button Not Functioning

### ISSUE THREAD

**Issue by ankitkumar1302** [stevdza-san/DiaryApp#6]
Issue Report: Login Button Not Functioning

Issue Description:
When attempting to log in by clicking the login button, the expected behaviour of a bottom sheet listing accounts does not occur. Despite waiting for an extended period, no response or UI element appears.

Steps to Reproduce:
1) Navigate to the login page of the project.
2) Click on the login button.
3) Observe the absence of any bottom sheet or account listing appearing.

Expected Behavior:
After clicking the login button, a bottom sheet should appear listing the available accounts for login.

Actual Behavior:
Nothing happens after clicking the login button. No bottom sheet or account listing is shown.

Additional Information:
A video demonstrating this issue has been attached to this report for further clarity.

Attachments:

https://github.com/stevdza-san/DiaryApp/assets/95230112/c6a30f1d-7f15-41a6-8e59-7348a40b8344

Environment:

Project Version: Latest
Operating System: Android 10

**Comment by stevdza-san** [comment]
Check the logs for "OneTapCompose" tag, to see some more information when trying to sign in.

**Comment by ankitkumar1302** [comment]
When I paste this tag 
i get these logs:-

2024-07-03 01:40:36.964 11400-11400 FloatService            com.miui.notes                       D  onPrimaryClipChanged OneTapCompose
2024-07-03 01:40:36.998 11400-11400 FloatService            com.miui.notes                       D  onPrimaryClipChanged OneTapCompose
2024-07-03 01:42:13.929 11400-11400 FloatService            com.miui.notes                       D  onPrimaryClipChanged 2024-07-03 01:40:36.964 11400-11400 FloatService            com.miui.notes                       D  onPrimaryClipChanged OneTapCompose
                                                                                                    2024-07-03 01:40:36.998 11400-11400 FloatService            com.miui.notes                       D  onPrimaryClipChanged OneTapCompose
2024-07-03 01:42:13.933 11400-11400 FloatService            com.miui.notes                       D  onPrimaryClipChanged 2024-07-03 01:40:36.964 11400-11400 FloatService            com.miui.notes                       D  onPrimaryClipChanged OneTapCompose
                                                                                                    2024-07-03 01:40:36.998 11400-11400 FloatService            com.miui.notes                       D  onPrimaryClipChanged OneTapCompose

What to do should I bypass this ? or something else.

**Comment by jakebasa** [comment]
have you found a solution for this?

**Comment by ankitkumar1302** [comment]
No, I did not find a solution for that, I think there are some other dependencies have to use to solve this or 
can modify the code to bypass this login function or straight goes to the app

**Comment by stevdza-san** [comment]
Usually that can happen because of the misconfigured google authentication provider, then because your device doesn't support Credential Manager API, or maybe your google account doesn't have enabled sign in prompts in the settings (https://myaccount.google.com/connections/settings?continue=https%3A%2F%2Fmyaccount.google.com%2Fdata-and-privacy). Either way you should be able to see some kind of an information in the logs when you click the button.

**Comment by JakeBasa** [comment]
still not fixed

**Comment by stevdza-san** [comment]
@JakeBasa Update the OneTapCompose library to 1.0.13, and check the logs after you press the button. Be sure to include your project's SHA-1 fingerprint and the package name in your Google Cloud Project.

**Comment by JakeBasa** [comment]
@stevdza-san Thanks for the fast reply, I can now select google accounts but this error occurs
![af3a7bbb-2b56-4315-9a71-5e20d2704fef](https://github.com/user-attachments/assets/8b014e93-e01c-4d7f-bbe6-165277686bca)

**Comment by stevdza-san** [comment]
That probably means you need to double check your Google Cloud project and see if you've configured it correctly. Remember you do need to use WEB client id in your app. Also double check if you're using the correct project package name, as well as SHA-1 fingerprint (in Android OAuth client)

**Comment by JakeBasa** [comment]
@stevdza-san does it mean I need to pay for Google Cloud Project? I thought it was free, i can't afford it yet. I'm a student in uni, and our professor asks us to find a sample android app and demonstrate how it works. We will present it tomorrow but i'm struggling with this part. Your help would mean a lot to me.

**Comment by stevdza-san** [comment]
@JakeBasa No, just go to the google cloud platform and create the project for free. I've made a video tutorial about it as well: https://youtu.be/QpaTcx2nnHM?si=PA9d5wJgrRA4gV3p

**Comment by JakeBasa** [comment]
@stevdza-san I followed the tutorial, i created the web client id and pasted it on the project's client id. But I cannot create an android client id:
![Screenshot 2024-07-21 201632](https://github.com/user-attachments/assets/18283eee-eff6-44ae-bca1-987637a8530a)
it still shows the same error:
![Screenshot 2024-07-21 204719](https://github.com/user-attachments/assets/f637e9e1-47c0-437f-989c-715363a1496f)

**Comment by stevdza-san** [comment]
@JakeBasa Ah, this error indicates that you already have a project on the Google Cloud Platform, that uses the same package name/SHA-1 fingerprint. Be sure that each project on the platform, includes unique package name.

**Comment by JakeBasa** [comment]
Do I need to configure things other than that? i did all the instructions, now it throws this:
[Service][AuthError(4346)] unauthorized. Server log entry: https://services.cloud.mongodb.com/groups/639f355942882a4bb5982f9a/apps/639f36eb2b997d15216b8c79/logs?co_id=669d118b651cec44f76461af

**Comment by JakeBasa** [comment]
I really appreciate your replies, I just need to get past this authentication part

**Comment by stevdza-san** [comment]
That error indicates that you have probably some permission issues on MongoDB Atlas. Check the logs first.
